//
//  Move.m
//  kickboxing app
//
//  Created by Bader on 5/19/20.
//  Copyright © 2020 Nebo. All rights reserved.
//

#import "Move.h"
#import "CategoryItem.h"

@implementation Move
//auto generated by compiler
-(id)initWithParams:(NSString*) name : (NSString *) imgStr : (MoveType) type : (MoveDifficulty) difficulty : (MoveDistance) distance : (BOOL) canRepeat : (NSArray *) nextArray {
    self = [super init];
    if(self) {
        self.name = name;
        self.imgStr = imgStr;
        self.moveType = type;
        self.moveDifficulty = difficulty;
        self.moveDistance = distance;
        self.algorithmBitmask = type | difficulty | distance;
        self.isActive = true;
        self.canRepeat = canRepeat;
        self.nextArray = nextArray;
    }
    return self;
}

@end
